packages/core/src/scd/scd-query.ts, packages/core/src/use-cases/uc-network-information.ts, packages/uilib/src/lib/components/accordion/cable-ied-accordion/cable-ied-accordion.svelte, packages/uilib/src/lib/plugins/network-explorer/diagram/diagram-container.svelte, packages/uilib/src/lib/plugins/network-explorer/sidebar/ied-accordion/ied-accordion.svelte
- ~~https://github.com/sprinteins/oscd-plugins/issues/7~~
- https://github.com/sprinteins/oscd-plugins/issues/24
- Cables in Sidenav Details are sorted by port
=> Select IEDs by cable and UI improvements

CHANGELOG.md, Readme.md, packages/plugins/network-explorer/package.json, packages/uilib/src/lib/components/accordion/cable-ied-accordion/cable-ied-accordion.svelte, packages/uilib/src/lib/components/accordion/cable-ied-accordion/index.ts, packages/uilib/src/lib/components/accordion/cable-ied-accordion/models.ts, packages/uilib/src/lib/plugins/network-explorer/sidebar/ied-accordion/ied-accordion.svelte, packages/uilib/src/lib/plugins/network-explorer/sidebar/new-connection/ied-port-select.svelte, packages/uilib/src/lib/plugins/network-explorer/sidebar/new-connection/new-connection.svelte
https://github.com/sprinteins/oscd-plugins/issues/6
=> feat(network explorer) ied further details 2

CHANGELOG.md, packages/plugins/network-explorer/package.json, packages/uilib/package.json, packages/uilib/src/lib/components/accordion/cable-ied-accordion/cable-ied-accordion.svelte, packages/uilib/src/lib/components/textfield/textfield.svelte, packages/uilib/src/lib/plugins/network-explorer/sidebar/new-connection/new-connection.svelte, packages/uilib/src/lib/plugins/network-explorer/sidebar/scd-assumptions/index.ts, packages/uilib/src/lib/plugins/network-explorer/sidebar/scd-assumptions/scd-assumptions.svelte, packages/uilib/src/lib/plugins/network-explorer/sidebar/sidebar.svelte, packages/uilib/src/lib/theme/theme.svelte, pnpm-lock.yaml
=> feat(ne): Cable name validation and diagram legend

.github/workflows/build.yml, .github/workflows/plugin_auto-doc.yml, .github/workflows/plugin_communication-explorer.yml, .github/workflows/plugin_documentation.yml, .github/workflows/plugin_io-center.yml, .github/workflows/plugin_network-explorer.yml, .github/workflows/plugin_type-designer.yml, .github/workflows/plugin_type-switcher.yml, packages/plugins/communication-explorer/package.json
Changes are made in `root > .github > .workflow > build.yml`
Closes #80
=> Deploy: fix github actions authentication

.github/pull_request_template.md
=> [PROPOSAL]:  PR template

packages/create-plugin/README.md, packages/create-plugin/template/src/plugin.svelte, packages/plugins/io-center/.vscode/extensions.json, packages/plugins/io-center/README.md, packages/plugins/io-center/index.html, packages/plugins/io-center/package.json, packages/plugins/io-center/postcss.config.js, packages/plugins/io-center/src/plugin.dev.ts, packages/plugins/io-center/src/plugin.svelte, packages/plugins/io-center/src/plugin.ts, packages/plugins/io-center/src/vite-env.d.ts, packages/plugins/io-center/svelte.config.js, packages/plugins/io-center/tailwind.config.ts, packages/plugins/io-center/tsconfig.json, packages/plugins/io-center/tsconfig.node.json, packages/plugins/io-center/vite.config.ts, pnpm-lock.yaml
io-center based on template init
=> IO-Center init

packages/plugins/io-center/package.json, packages/plugins/io-center/src/ui/components/object-tree/object-tree.svelte, packages/plugins/io-center/src/ui/components/object-tree/tree-node.svelte, pnpm-lock.yaml
=> Object Tree adjustments

packages/plugins/communication-explorer/package.json, packages/uilib/src/lib/components/diagram/diagram.svelte
resolves:
- https://github.com/sprinteins/oscd-plugins/issues/296
=> Fix: Communication Explorer Hijacks Space

packages/uilib/src/lib/components/diagram/ied-element/ied-element.svelte, packages/uilib/src/lib/plugins/communication-explorer/communication-explorer.svelte, packages/uilib/src/lib/plugins/communication-explorer/sidebar/sidebar.svelte
When the OS or the openscd theme was set on dark, the plugin was not usable
-> enforce of the use of light theme + change some colors to go along.
Closes #299
=> fix: communication explorer color issue

pnpm-lock.yaml
Currently the autodoc build is failing because of the lock.yaml [file](https://github.com/sprinteins/oscd-plugins/actions/runs/13434832720/job/37534688540)
=> Fix pnpm-lock.yaml file for build

packages/plugins/io-center/src/headless/constants/constants.ts, packages/plugins/io-center/src/headless/stores/canvas-operations.svelte.ts, packages/plugins/io-center/src/plugin.svelte, packages/plugins/io-center/src/ui/components/lp-list/filter-buttons.svelte, packages/plugins/io-center/src/ui/components/lp-list/lp-element.svelte, packages/plugins/io-center/src/ui/components/lp-list/lp-list.svelte, packages/plugins/io-center/src/ui/components/lp-list/types.lp-list.d.ts, packages/plugins/io-center/src/ui/components/object-tree/object-tree.svelte, packages/plugins/io-center/src/ui/components/search-bar.svelte
=> I/O Center LP bar

packages/plugins/io-center/src/headless/stores/canvas-operations.svelte.ts, packages/plugins/io-center/src/ui/components/object-tree/object-tree.svelte, packages/plugins/io-center/src/ui/components/object-tree/tree-node.svelte, pnpm-lock.yaml
#
https://github.com/user-attachments/assets/411f47a2-1bf0-44b0-9799-2fe8c07a4753
#
=> Feature: Single and Multi select objects

packages/plugins/auto-doc/src/stores/signallist.store.ts
=> [FEATURE]: Add logic for identifying bay and voltageLevel of message publisher

packages/plugins/auto-doc/CHANGELOG.md, packages/plugins/auto-doc/package.json, packages/plugins/auto-doc/vite.config.ts
=> [BUGFIX]: Fix build of autodoc

packages/uilib/src/lib/components/diagram/diagram.svelte
fixing large zoom bug when using focus mode in communication explorer
#
#
=> fixing way too large zoom sometimes happening when using focus mode

packages/plugins/auto-doc/CHANGELOG.md, packages/plugins/auto-doc/package.json, packages/plugins/auto-doc/src/components/data-table/data-table.svelte, packages/plugins/auto-doc/src/pages/template-overview/template-overview.svelte, packages/plugins/auto-doc/src/stores/doc-templates.store.spec.ts, packages/plugins/auto-doc/src/stores/doc-templates.store.ts
#142 
#
https://github.com/user-attachments/assets/e82253c9-0fbf-4a6b-8379-b1d87b091f86
=> [FEATURE]: Duplicate Template

packages/plugins/auto-doc/CHANGELOG.md, packages/plugins/auto-doc/package.json, packages/plugins/auto-doc/src/utils/pdfGenerator.ts, pnpm-lock.yaml
Disclaimer: For changelog's sake, please merge the branches in the following order: 
[# 351](https://github.com/sprinteins/oscd-plugins/pull/350) -> [# 323](https://github.com/sprinteins/oscd-plugins/pull/349) -> [# 172](https://github.com/sprinteins/oscd-plugins/pull/348)
#
Excel export: Fila name **hello-world.xlsx**
Code Required on **pdfGenerator**:
#
=> [FEAT]: Use Zipcelx library to export Signal List as Excel

packages/plugins/io-center/src/command.svelte.ts, packages/plugins/io-center/src/headless/constants/constants.ts, packages/plugins/io-center/src/plugin.svelte, packages/plugins/io-center/src/ui/components/canvas/canvas-area.svelte, packages/plugins/io-center/src/ui/components/canvas/canvas-store.svelte.ts, packages/plugins/io-center/src/ui/components/canvas/edit-lc-dialog.svelte, packages/plugins/io-center/src/ui/components/canvas/node-element.svelte, packages/plugins/io-center/src/ui/components/canvas/types.canvas.d.ts, packages/plugins/io-center/src/ui/components/common/edit-button.svelte, packages/plugins/io-center/src/ui/components/lp-list/types.lp-list.d.ts
Demo:
https://github.com/user-attachments/assets/942ef240-dc07-4fc4-8e60-6cf1fd019b2d
=> I/O Center: Edit LC

packages/plugins/auto-doc/CHANGELOG.md, packages/plugins/auto-doc/src/components/element-wrapper/element-wrapper.svelte, packages/plugins/auto-doc/src/components/template-builder/template-builder.svelte, packages/plugins/auto-doc/src/plugin.svelte, packages/plugins/auto-doc/src/stores/doc-templates.store.spec.ts, packages/plugins/auto-doc/src/stores/doc-templates.store.ts, packages/plugins/auto-doc/src/stores/events.store.ts, packages/plugins/auto-doc/src/stores/plugin.store.ts
Clicking the duplicate button will duplicate the according block with its contents. #273.
#
=> feat: duplicate modul

packages/plugins/io-center/src/command.svelte.ts, packages/plugins/io-center/src/headless/constants/constants.ts, packages/plugins/io-center/src/headless/stores/document-helpers.svelte.ts, packages/plugins/io-center/src/plugin.svelte, packages/plugins/io-center/src/ui/components/canvas/add-lc-dialog.svelte, packages/plugins/io-center/src/ui/components/canvas/canvas-area.svelte, packages/plugins/io-center/src/ui/components/canvas/node-element.svelte, packages/plugins/io-center/src/ui/components/canvas/types.canvas.d.ts, packages/plugins/io-center/src/ui/components/common/input.svelte, packages/plugins/io-center/src/ui/components/common/select.svelte, packages/plugins/io-center/src/ui/components/lp-list/create-lp-dialog.svelte, packages/plugins/io-center/src/ui/components/lp-list/lp-list.svelte, packages/plugins/io-center/src/ui/components/lp-list/types.lp-list.d.ts
=> I/O Center: fill missing LNodeType

packages/plugins/communication-explorer/src/plugin.ts, packages/plugins/documentation/src/plugin.ts, packages/plugins/network-explorer/src/plugin.ts, packages/plugins/type-switcher/src/plugin.ts
Destroy main svelte component on plugin destroy
closes #327
=> fix: Unmount svelte component on plugin destroy

packages/plugins/type-designer/CHANGELOG.md, packages/plugins/type-designer/package.json, packages/plugins/type-designer/src/headless/stores/sidebar.svelte.ts, packages/plugins/type-designer/src/headless/stores/type-elements/store.svelte.ts, packages/plugins/type-designer/src/ui/components/import/import-select.svelte, packages/plugins/type-designer/src/ui/components/sidebar-wrapper.svelte
This PR add validation to input name in the sidebar
Closes #381
=> fix(type-designer): add validation to input name in the sidebar

.github/workflows/build.yml
After updating the script in package.json, the build script of gh actions also needed an update.
=> fix(gh-actions): change the install script

packages/plugins/type-designer/CHANGELOG.md, packages/plugins/type-designer/package.json, packages/plugins/type-designer/src/headless/stores/type-elements/consolidate-types.helper.ts, packages/plugins/type-designer/src/headless/stores/type-elements/types.d.ts, packages/plugins/type-designer/src/ui/components/element-card/card-collapsible-wrapper.svelte
This PR adds an occurrence to the refs name
[d1c59d7](https://github.com/sprinteins/oscd-plugins/pull/386/commits/d1c59d7bd63f6ac0c0a1222c6654326543b9dfca)
Closes #310
=> feat(type-designer): add ref occurrence

packages/plugins/type-designer/CHANGELOG.md, packages/plugins/type-designer/package.json
=> DND Adaptions - Upgrade version

packages/plugins/io-center/src/headless/constants/constants.ts, packages/plugins/io-center/src/ied/object-tree.type.d.ts, packages/plugins/io-center/src/query.svelte.ts, packages/plugins/io-center/src/ui/components/object-tree/object-tree.svelte
=> Show Access Points in DO Bar

packages/plugins/io-center/src/plugin.svelte, packages/plugins/io-center/src/query.svelte.ts, packages/plugins/io-center/src/store.svelte.ts, packages/plugins/io-center/src/ui/components/canvas/canvas-store.svelte.ts, packages/plugins/io-center/src/ui/components/canvas/ports.svelte, packages/plugins/io-center/src/ui/components/canvas/types.canvas.d.ts, packages/plugins/io-center/src/ui/components/lp-list/lp-element.svelte
https://github.com/user-attachments/assets/3eba3599-1fa9-48a6-af4d-09981f44f689
=> I/O Center: LP Selection Improvments

packages/plugins/auto-doc/CHANGELOG.md, packages/plugins/auto-doc/package.json, packages/plugins/auto-doc/src/components/elements/text-element/text-element.svelte, packages/plugins/auto-doc/src/utils/pdfGenerator.ts
Previous behavior:
When the user types {{//@name}} placeholder,   all the values found are saved into the scd file. Whenever the user edits the template, the typed placeholder of {{//@name}} is gone and completely replaced by the values in the scd
Current behavior:
Now the {{//@name}} placeholder is saved on the scd and the values are only searched once the user wants to generate a pdf. Meaning if the user then edits a given template, the pre defined placeholder is to be seen
1. Click on Doc demo
2. Fill in **{{//default:Substation/@name}} Lorem ipsum dolor sit amet, consetetur sadipscing elitr, ....etc...**
3. PDF Result
You can add specific commits which are worth …
=> [BUGFIX]: Fill placeholder on pdf generation

packages/plugins/type-designer/CHANGELOG.md, packages/plugins/type-designer/package.json
This PR is a version and changelog update (3.10) to trigger gh actions build.
=> feat(type-designer): increment version + changelog update

packages/plugins/type-designer/CHANGELOG.md, packages/plugins/type-designer/package.json, packages/plugins/type-designer/src/ui/components/element-card/card-collapsible-wrapper.svelte
This PR fixes an import issue (erased by merge) + resolves an issue on allowed dropzones.
=> fix(type-designer): resolve import statement & restrict dnd dropzones

packages/core/standard/src/ed2/rev1/stable/constants/equipments.ts
=> Add load tap changer

packages/plugins/type-designer/src/headless/stores/type-elements/store.svelte.ts, packages/plugins/type-designer/src/headless/stores/type-elements/type-naming.helper.ts
https://github.com/user-attachments/assets/66cef6f4-bcbe-4444-8349-617b4ba1368e
=> Create an element with the same name after deletion

packages/plugins/auto-doc/src/components/elements/signal-list-element/signal-list-element.svelte
"Message Types" Subtitle is missing in Signallist
=> "Message Types" Subtitle is missing in Signallist

packages/plugins/io-center/CHANGELOG.md, packages/plugins/io-center/package.json, packages/plugins/io-center/src/headless/stores/canvas/connection-crud.helper.ts, packages/plugins/io-center/src/headless/stores/canvas/store.svelte.ts, packages/plugins/io-center/src/headless/stores/ied/crud-operation.helper.ts, packages/plugins/io-center/src/headless/stores/ied/store.svelte.ts, packages/plugins/io-center/src/headless/stores/ied/tree-consolidation.helpers.ts, packages/plugins/io-center/src/headless/stores/ied/tree.helper.ts, packages/plugins/io-center/src/headless/stores/ied/types.d.ts, packages/plugins/io-center/src/headless/stores/logical/common-crud-operation.helper.ts, packages/plugins/io-center/src/headless/stores/logical/store.svelte.ts, packages/plugins/io-center/src/headless/stores/types.d.ts, packages/plugins/io-center/src/headless/utils/index.ts, packages/plugins/io-center/src/headless/utils/utils.ts, packages/plugins/io-center/src/plugin.svelte, packages/plugins/io-center/src/ui/canvas/columns.svelte, packages/plugins/io-center/src/ui/canvas/node-card.svelte, packages/plugins/io-center/src/ui/canvas/port.svelte, packages/plugins/io-center/src/ui/layout.svelte, packages/plugins/io-center/src/ui/sidebar-left/ied-tree.svelte, packages/plugins/io-center/src/ui/sidebar-left/sidebar-left.svelte, packages/plugins/io-center/src/ui/sidebar-right/logical-dialog.svelte
Enable multiple data objects selection.
=> Fix: io-center Data Object selection

packages/plugins/auto-doc/CHANGELOG.md, packages/plugins/auto-doc/package.json, packages/plugins/auto-doc/src/ui/components/elements/signal-list-element/signal-list-element.svelte, packages/plugins/auto-doc/src/ui/components/elements/signal-list-element/signal-row.svelte
=> Fix: Signal list dnd
